name: gdb-static
adopt-info: gdb
license: GPL-3.0-or-later
summary: GDB as a static binary
description: |
  gdb & gdbserver, the go-to debugging tools for GNU/Linux and *BSD systems.
  This provides a minimalized and static build for all supported systems.

  Note: To use this debugger, please start it outside of confinement, ie execute it directly:

  `/snap/gdb-static/current/usr/bin/gdb`

  `/snap/gdb-static/current/usr/bin/gdbserver`

confinement: strict
build-base: core24
base: bare
source-code: https://github.com/fredldotme/binutils-gdb-static
website: https://sourceware.org/gdb/current/
issues: https://github.com/fredldotme/gdb-static-snap/issues
compression: lzo

platforms:
  arm64:
    build-on: [arm64]
  amd64:
    build-on: [amd64]
  armhf:
    build-on: [armhf]
  ppc64el:
    build-on: [ppc64el]
  riscv64:
    build-on: [riscv64]
  s390x:
    build-on: [s390x]

apps:
  gdb-static:
    command: usr/bin/gdb

lint:
  ignore:
    - classic
    - library

parts:
  gdb:
    source: https://github.com/fredldotme/binutils-gdb-static.git
    source-branch: gdb-static-17.1
    source-depth: 1
    plugin: nil
    override-pull: |
      craftctl default
    override-build: |
      cd $CRAFT_PART_SRC
      craftctl set version="17.1"
      ./configure --prefix=/usr \
          --enable-static \
          --disable-interprocess-agent \
          --disable-inprocess-agent \
          --without-expat \
          --with-static-standard-libraries \
          --disable-tui \
          LDFLAGS='-static'
      make all-gdb all-gdbserver -j$(nproc --all)
      DESTDIR=$CRAFT_PART_INSTALL make install-gdb install-gdbserver
      craftctl default
    override-stage: |
      craftctl default
    override-prime: |
      craftctl default
    build-packages:
      - build-essential
      - bison
      - flex
      - autoconf
      - gettext
      - texinfo
      - libgmp-dev
      - libmpfr-dev
    prime:
      - usr/bin/gdb
      - usr/bin/gdbserver
      - -usr/share
      - -usr/lib
      - -usr/include
